/*
 *    Copyright (C) 2016-2026 Grok Image Compression Inc.
 *
 *    This source code is free software: you can redistribute it and/or  modify
 *    it under the terms of the GNU Affero General Public License, version 3,
 *    as published by the Free Software Foundation.
 *
 *    This source code is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License for more details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * ResWindow
 *
 * Manage all buffers for a single DWT resolution. This class
 * stores a buffer for the resolution (in REL coordinates),
 * and also buffers for the 4 sub-bands generated by the DWT transform
 * (in Canvas coordinates).
 *
 * Note: if highest resolution window is set, then only this window allocates
 * memory, and all other ResWindow buffers attach themselves to the highest resolution buffer
 *
 */

/*
 Various coordinate systems are used to describe regions in the tile component buffer.

 1) Canvas coordinates:  JPEG 2000 global image coordinates.

 2) Tile component coordinates: canvas coordinates with sub-sampling applied

 3) Band coordinates: coordinates relative to a specified sub-band's origin

 4) Buffer coordinates: coordinate system where all resolutions are translated
  to common origin (0,0). If each code block is translated relative to the origin of the
 resolution that **it belongs to**, the blocks are then all in buffer coordinate system

 Note: the name of any method or variable returning non canvas coordinates is appended
 with "REL", to signify relative coordinates.

 */

#pragma once

#include "ResSimple.h"

namespace grk
{

enum eSplitOrientation
{
  SPLIT_L,
  SPLIT_H,
  SPLIT_NUM_ORIENTATIONS
};

template<typename T>
struct TileComponentWindow;
template<typename T>
struct TileComponentWindowBase;

template<typename T>
struct ResWindow
{
  friend struct TileComponentWindowBase<T>;
  friend struct TileComponentWindow<T>;
  typedef Buffer2d<T, AllocatorAligned> Buf2dAligned;

private:
  ResWindow(uint8_t resno, Buf2dAligned* resWindowHighestResREL, ResSimple tileCompAtRes,
            ResSimple tileCompAtLowerRes, Rect32 resWindow, Rect32 tileCompWindowUnreduced,
            Rect32 tileCompUnreduced, uint32_t FILTER_WIDTH, DecompositionSplit split,
            uint8_t numDecompsX, uint8_t numDecompsY)
      : allocated_(false), filterWidth_(FILTER_WIDTH), tileCompAtRes_(tileCompAtRes),
        tileCompAtLowerRes_(tileCompAtLowerRes), resWindowBuffer_(new Buf2dAligned(resWindow)),
        resWindowBufferSplit_{nullptr, nullptr},
        resWindowBufferHighestResREL_(resWindowHighestResREL),
        resWindowBufferREL_(new Buf2dAligned(resWindow.width(), resWindow.height())),
        resWindowBufferSplitREL_{nullptr, nullptr}
  {
    resWindowBuffer_->setOrigin(tileCompAtRes_);
    Rect32 resWindowPadded;
    for(uint8_t orient = 0; orient < ((resno) > 0 ? t1::BAND_NUM_ORIENTATIONS : 1); orient++)
    {
      // DFS can omit HL, LH or HH.
      if(resno > 0 && orient != t1::BAND_ORIENT_LL && !ResSimple::hasBand(split, orient))
      {
        bandWindowsBoundsPadded_.push_back(Rect32());
        continue;
      }
      // todo: should only need padding equal to FILTER_WIDTH, not 2*FILTER_WIDTH
      auto bandWindow =
          getPaddedBandWindow(numDecompsX, numDecompsY, split, orient, tileCompWindowUnreduced,
                              tileCompUnreduced, 2 * FILTER_WIDTH, resWindowPadded);
      Rect32 band = tileCompAtRes_.tileBand[t1::BAND_ORIENT_LL];
      if(resno > 0)
        band = orient == t1::BAND_ORIENT_LL ? Rect32(tileCompAtLowerRes_)
                                            : tileCompAtRes_.tileBand[orient - 1];
      bandWindow.setOrigin(band);
      assert(bandWindow.intersection(band).setOrigin(bandWindow) == bandWindow);
      bandWindowsBoundsPadded_.push_back(bandWindow);
    }
    // windowed decompression
    if(FILTER_WIDTH)
    {
      if(tileCompAtLowerRes_.numTileBandWindows)
      {
        assert(resno > 0);
        resWindowBuffer_->setRect(resWindowPadded);
        resWindowBufferREL_->setRect(resWindowBuffer_->toRelative());

        for(uint8_t orient = 0; orient < t1::BAND_NUM_ORIENTATIONS; orient++)
        {
          auto bandWindow = bandWindowsBoundsPadded_[orient];
          bandWindowsBuffersPadded_.push_back(new Buf2dAligned(bandWindow, true));
          bandWindowsBuffersPaddedREL_.push_back(new Buf2dAligned(bandWindow.toRelative(), true));
        }
        genSplitWindowBuffers(resWindowBufferSplit_, resWindowBuffer_,
                              bandWindowsBuffersPadded_[t1::BAND_ORIENT_LL],
                              bandWindowsBuffersPadded_[t1::BAND_ORIENT_LH], false);
        genSplitWindowBuffers(resWindowBufferSplitREL_, resWindowBuffer_,
                              bandWindowsBuffersPadded_[t1::BAND_ORIENT_LL],
                              bandWindowsBuffersPadded_[t1::BAND_ORIENT_LH], true);
      }
    }
    else
    {
      // slot 0 is a placeholder for LL, the rest stay empty when the level does not split that way
      if(tileCompAtLowerRes_.numTileBandWindows && tileCompAtLowerRes_.valid())
      {
        bandWindowsBuffersPadded_.push_back(new Buf2dAligned(0, 0));
        bandWindowsBuffersPaddedREL_.push_back(new Buf2dAligned(0, 0));
        for(uint8_t orientation = t1::BAND_ORIENT_HL; orientation < t1::BAND_NUM_ORIENTATIONS;
            ++orientation)
        {
          if(!ResSimple::hasBand(split, orientation))
          {
            bandWindowsBuffersPadded_.push_back(new Buf2dAligned(0, 0));
            bandWindowsBuffersPaddedREL_.push_back(new Buf2dAligned(0, 0));
            continue;
          }
          auto band = Rect32(tileCompAtRes_.tileBand + orientation - 1);
          bandWindowsBuffersPadded_.push_back(new Buf2dAligned(band));
          bandWindowsBuffersPaddedREL_.push_back(new Buf2dAligned(band.toRelative()));
        }
        bool splitsY = splitsVertically(split);
        for(uint8_t i = 0; i < SPLIT_NUM_ORIENTATIONS; i++)
        {
          Rect32 splitWindow = Rect32(resWindowBuffer_);
          if(splitsY)
          {
            splitWindow.y0 =
                (resWindowBuffer_->y0 == 0 ? 0
                                           : ceildivpow2<uint32_t>(resWindowBuffer_->y0 - i, 1));
            splitWindow.y1 =
                (resWindowBuffer_->y1 == 0 ? 0
                                           : ceildivpow2<uint32_t>(resWindowBuffer_->y1 - i, 1));
            // the origin has to be halved along with y0 and y1, otherwise toRelative() underflows
            splitWindow.origin_y0 =
                (resWindowBuffer_->origin_y0 == 0
                     ? 0
                     : ceildivpow2<uint32_t>(resWindowBuffer_->origin_y0 - i, 1));
          }
          else if(i == SPLIT_H)
          {
            // a horizontal only level keeps every row in the low split
            splitWindow.y0 = splitWindow.y1;
          }
          resWindowBufferSplit_[i] = new Buf2dAligned(splitWindow);
          resWindowBufferSplitREL_[i] = new Buf2dAligned(splitWindow.toRelative());
        }
      }
    }
  }
  ~ResWindow()
  {
    delete resWindowBufferREL_;
    for(auto& b : bandWindowsBuffersPaddedREL_)
      delete b;
    for(uint32_t i = 0; i < SPLIT_NUM_ORIENTATIONS; ++i)
      delete resWindowBufferSplitREL_[i];

    delete resWindowBuffer_;
    for(auto& b : bandWindowsBuffersPadded_)
      delete b;
    for(uint32_t i = 0; i < SPLIT_NUM_ORIENTATIONS; ++i)
      delete resWindowBufferSplit_[i];
  }
  void genSplitWindowBuffers(Buf2dAligned** resWindowBufferSplit, Buf2dAligned* resWindowBuffer,
                             Buf2dAligned* bandWindowsBuffersPaddedXL,
                             Buf2dAligned* bandWindowsBuffersPaddedXH, bool useRelative)
  {
    auto lowerRes =
        useRelative ? Rect32(tileCompAtLowerRes_).toRelative() : Rect32(tileCompAtLowerRes_);
    auto xlBounds = useRelative ? Rect32(bandWindowsBuffersPaddedXL).toRelative()
                                : Rect32(bandWindowsBuffersPaddedXL);
    auto xhBounds = useRelative ? Rect32(bandWindowsBuffersPaddedXH).toRelative()
                                : Rect32(bandWindowsBuffersPaddedXH);
    auto resWin = useRelative ? Rect32(resWindowBuffer).toRelative() : Rect32(resWindowBuffer);

    // two windows formed by horizontal pass and used as input for vertical pass
    auto splitResWindowBounds = Rect32(resWin.x0, xlBounds.y0, resWin.x1, xlBounds.y1);
    resWindowBufferSplit[SPLIT_L] = new Buf2dAligned(splitResWindowBounds);

    splitResWindowBounds =
        Rect32(resWin.x0, lowerRes.y1 + xhBounds.y0, resWin.x1, lowerRes.y1 + xhBounds.y1);
    resWindowBufferSplit[SPLIT_H] = new Buf2dAligned(splitResWindowBounds);
  }
  bool alloc(bool clear)
  {
    if(allocated_)
      return true;

    // if top level window is present, then all buffers attach to this window
    if(resWindowBufferHighestResREL_)
    {
      // ensure that top level window is allocated
      if(!resWindowBufferHighestResREL_->alloc2d(clear))
        return false;

      // don't allocate bandWindows for windowed decompression
      if(filterWidth_)
        return true;

      // attach to top level window
      if(resWindowBufferREL_ != resWindowBufferHighestResREL_)
        resWindowBufferREL_->attach(resWindowBufferHighestResREL_);

      // tileCompResLower_ is null for lowest resolution
      if(tileCompAtLowerRes_.numTileBandWindows)
      {
        for(uint8_t orientation = 0; orientation < bandWindowsBuffersPaddedREL_.size();
            ++orientation)
        {
          switch(orientation)
          {
            case t1::BAND_ORIENT_HL:
              bandWindowsBuffersPaddedREL_[orientation]->attach(resWindowBufferHighestResREL_,
                                                                tileCompAtLowerRes_.width(), 0);
              break;
            case t1::BAND_ORIENT_LH:
              bandWindowsBuffersPaddedREL_[orientation]->attach(resWindowBufferHighestResREL_, 0,
                                                                tileCompAtLowerRes_.height());
              break;
            case t1::BAND_ORIENT_HH:
              bandWindowsBuffersPaddedREL_[orientation]->attach(resWindowBufferHighestResREL_,
                                                                tileCompAtLowerRes_.width(),
                                                                tileCompAtLowerRes_.height());
              break;
            default:
              break;
          }
        }
        resWindowBufferSplit_[SPLIT_L]->attach(resWindowBufferHighestResREL_);
        resWindowBufferSplit_[SPLIT_H]->attach(resWindowBufferHighestResREL_, 0,
                                               tileCompAtLowerRes_.height());
      }

      // attach canvas windows to relative windows
      for(uint8_t orientation = 0; orientation < bandWindowsBuffersPaddedREL_.size(); ++orientation)
      {
        bandWindowsBuffersPadded_[orientation]->attach(bandWindowsBuffersPaddedREL_[orientation]);
      }
      resWindowBuffer_->attach(resWindowBufferREL_);
      for(uint8_t i = 0; i < SPLIT_NUM_ORIENTATIONS; ++i)
      {
        if(resWindowBufferSplitREL_[i])
          resWindowBufferSplitREL_[i]->attach(resWindowBufferSplit_[i]);
      }
    }
    else
    {
      // 1. allocate resolution window
      // resolution window is always allocated
      if(!resWindowBufferREL_->alloc2d(clear))
        return false;
      resWindowBuffer_->attach(resWindowBufferREL_);

      // 2, allocate padded band windows
      // band windows are allocated if present
      for(auto& b : bandWindowsBuffersPadded_)
      {
        if(!b->alloc2d(clear))
          return false;
      }
      for(uint8_t orientation = 0; orientation < bandWindowsBuffersPaddedREL_.size(); ++orientation)
      {
        bandWindowsBuffersPaddedREL_[orientation]->attach(
            bandWindowsBuffersPaddedREL_[orientation]);
      }

      // 3. allocate split windows
      if(tileCompAtLowerRes_.numTileBandWindows)
      {
        if(resWindowBufferHighestResREL_)
        {
          resWindowBufferSplit_[SPLIT_L]->attach(resWindowBuffer_);
          resWindowBufferSplit_[SPLIT_H]->attach(resWindowBuffer_, 0, tileCompAtLowerRes_.height());
        }
        else
        {
          resWindowBufferSplit_[SPLIT_L]->alloc2d(clear);
          resWindowBufferSplit_[SPLIT_H]->alloc2d(clear);
        }
        for(uint8_t i = 0; i < SPLIT_NUM_ORIENTATIONS; ++i)
        {
          if(resWindowBufferSplitREL_[i])
            resWindowBufferSplitREL_[i]->attach(resWindowBufferSplit_[i]);
        }
      }
    }

    allocated_ = true;

    return true;
  }

  /**
   * Get band window (in tile component coordinates) for specified number
   * of decompositions (with padding)
   *
   * Note: if numDecomps is zero, then the band window (and there is only one)
   * is equal to the unreduced tile component window (with padding)
   */
  static Rect32 getPaddedBandWindow(uint8_t numDecompsX, uint8_t numDecompsY,
                                    DecompositionSplit split, uint8_t orientation,
                                    Rect32 unreducedTileCompWindow, Rect32 unreducedTileComp,
                                    uint32_t padding, Rect32& paddedResWindow)
  {
    assert(orientation < t1::BAND_NUM_ORIENTATIONS);
    if(numDecompsX == 0 && numDecompsY == 0)
    {
      assert(orientation == 0);
      return unreducedTileCompWindow.grow_IN_PLACE(padding).intersection(&unreducedTileComp);
    }
    // decompositions left once this level is undone
    uint8_t lowerX = (uint8_t)(numDecompsX - (splitsHorizontally(split) ? 1 : 0));
    uint8_t lowerY = (uint8_t)(numDecompsY - (splitsVertically(split) ? 1 : 0));
    paddedResWindow = ResSimple::getBandWindow(lowerX, lowerY, 0, unreducedTileCompWindow);
    auto oneLessDecompTile = ResSimple::getBandWindow(lowerX, lowerY, 0, unreducedTileComp);
    paddedResWindow.grow_IN_PLACE(2 * padding).clip_IN_PLACE(oneLessDecompTile);
    // the partial inverse wavelet indexes both sub-band windows off one interleaved
    // position, which only lines up when the window and the resolution share a parity
    if(paddedResWindow.x0 > oneLessDecompTile.x0 &&
       ((paddedResWindow.x0 ^ oneLessDecompTile.x0) & 1))
      paddedResWindow.x0--;
    if(paddedResWindow.y0 > oneLessDecompTile.y0 &&
       ((paddedResWindow.y0 ^ oneLessDecompTile.y0) & 1))
      paddedResWindow.y0--;
    paddedResWindow.setOrigin(oneLessDecompTile);

    return ResSimple::getBandWindow(splitsHorizontally(split) ? 1 : 0,
                                    splitsVertically(split) ? 1 : 0, orientation, paddedResWindow);
  }

  Buffer2dSimple<T> getResWindowBufferSimple(void) const
  {
    return resWindowBuffer_->simple();
  }
  Buffer2dSimple<float> getResWindowBufferSimpleF(void) const
  {
    return resWindowBuffer_->simpleF();
  }
  void disableBandWindowAllocation(void)
  {
    resWindowBufferHighestResREL_ = resWindowBufferREL_;
  }
  Buf2dAligned* getResWindowBufferSplitREL(eSplitOrientation orientation) const
  {
    return resWindowBufferSplitREL_[orientation];
  }
  const Rect32* getBandWindowPadded(t1::eBandOrientation orientation) const
  {
    return &bandWindowsBoundsPadded_[orientation];
  }
  const Buf2dAligned* getBandWindowBufferPaddedREL(t1::eBandOrientation orientation) const
  {
    return bandWindowsBuffersPaddedREL_[orientation];
  }
  const Buffer2dSimple<T> getBandWindowBufferPaddedSimple(t1::eBandOrientation orientation) const
  {
    return bandWindowsBuffersPadded_[orientation]->simple();
  }
  const Buffer2dSimple<float>
      getBandWindowBufferPaddedSimpleF(t1::eBandOrientation orientation) const
  {
    return bandWindowsBuffersPadded_[orientation]->simpleF();
  }
  Buf2dAligned* getResWindowBufferREL(void) const
  {
    return resWindowBufferREL_;
  }
  bool allocated_;
  uint32_t filterWidth_;

  ResSimple tileCompAtRes_; // numTileBandWindows> 0 will trigger creation of band window buffers
  ResSimple tileCompAtLowerRes_; // numTileBandWindows==0 for lowest resolution

  Buf2dAligned* resWindowBuffer_;
  Buf2dAligned* resWindowBufferSplit_[SPLIT_NUM_ORIENTATIONS];
  std::vector<Buf2dAligned*> bandWindowsBuffersPadded_;

  /*
  bandWindowsBoundsPadded_ is used for determining which precincts and code blocks overlap
  the window of interest, in each respective resolution
  */
  std::vector<Rect32> bandWindowsBoundsPadded_;

  Buf2dAligned* resWindowBufferHighestResREL_;
  Buf2dAligned* resWindowBufferREL_;
  Buf2dAligned* resWindowBufferSplitREL_[SPLIT_NUM_ORIENTATIONS];
  std::vector<Buf2dAligned*> bandWindowsBuffersPaddedREL_;
};

} // namespace grk
